export enum StudyDomain {
    HISTOIRE = "HISTOIRE",
    GEOGRAPHIE = "GEOGRAPHIE",
    MATHEMATIQUES = "MATHEMATIQUES",
    PHYSIQUE = "PHYSIQUE",
    CHIMIE = "CHIMIE",
    INFORMATIQUE = "INFORMATIQUE",
    DROIT = "DROIT",
    LETTRES = "LETTRES",
    MEDECINE = "MEDECINE",
    SPORT = "SPORT"
}
