export enum StudyCountry {
  FRANCE = "FRANCE",
  ALLEMAGNE = "ALLEMAGNE",
  ESPAGNE = "ESPAGNE",
  ANGLETERRE = "ANGLETERRE",
  ECOSSE = "ECOSSE",
  IRLANDE = "IRLANDE",
  BELGIQUE = "BELGIQUE",
  PAYSBAS = "PAYS-BAS",
  PORTUGAL = "PORTUGAL",
  ITALIE = "ITALIE",
  AUTRICHE = "AUTRICHE",
  FINLANDE = "FINLANDE",
  NORVEGE = "NORVEGE",
  SUEDE = "SUEDE",
  DANEMARK = "DANEMARK"
}
